name: Build and Deploy Unity Game to Google Play
on:
  workflow_dispatch:
jobs:
  release:
    uses: zhukovskygamesstudio/workflows/.github/workflows/googleplay.yml@main 
    with:
      unity_version:  ${{ vars.UNITY_VERSION }}
      android_keystore_name:  ${{ vars.GP_KEYSTORE_NAME }}
      gp_package_name:  ${{ vars.GP_PACKAGE_NAME }}
    secrets:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      ANDROID_KEYSTORE_PASS: ${{ secrets.ANDROID_KEYSTORE_PASS }}
      ANDROID_ALIAS_PASS: ${{ secrets.ANDROID_ALIAS_PASS }}
      GOOGLE_PLAY_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT }}
